[package]
name = "Streaming_algorithms_comparison"
version = "1.0.0"
default-run = "comparison"

[workspace]
members = [
	"gumbel_estimation",
	"comparison",
	"gen_data",
]
resolver = "2"

[profile.release]
debug = true
strip = false
